version: "3.7"
services: 
    db:
        image: postgres
        container_name: postgres
        networks: 
            - webnet
        volumes: 
            - pgdata:/var/lib/postgresql/data
        ports: 
            - "5434:5432"
    web:
        image: tolumide/recs
        container_name: server
        depends_on:
            - db
        ports:
            - 8000:8000
        networks: 
            - webnet
        environment: 
            DATABASE_URL: ${DATABASE_URL}
            SECRET_KEY: ${SECRET_KEY}
            ROCKET_DATABASES: ${ROCKET_DATABASES}
        entrypoint: ["/bin/bash", "./entrypoint.sh"]
networks:
    webnet:
volumes:
    pgdata:
    static_volume: